### ISSUE TITLE
When will update to mapnik4.0.2??

### ISSUE THREAD

**Issue by yh371174229** [CartoDB/node-mapnik#31]
When will update to mapnik4.0.2?? is there a plan??

**Comment by Algunenano** [comment]
Hi, node-mapnik 4.0.2 is based on Mapnik 4.0 which is still under development so I don't see us updating it as of yet.

Are there any functionalities or fixed issues that you are missing from upstream Mapnik/node-mapnik?

**Comment by yh371174229** [comment]
no bug find，I just use tilelive-mapnik which uses node-mapnik,I hope to  use the latest mapnik,so come here and ask this question.Thanks for answering
